# Generated by Django 3.2.18 on 2023-05-08 09:45

import Masterlist.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rev_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Document_Description', models.CharField(blank=True, max_length=256, null=True)),
                ('Rev_No', models.CharField(blank=True, max_length=256, null=True)),
                ('Rev_Date', models.DateField(blank=True, null=True)),
                ('Rev_History', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Master_Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.DateTimeField(auto_now=True)),
                ('Document_No', models.CharField(blank=True, max_length=256, null=True)),
                ('Document_Description', models.CharField(blank=True, max_length=256, null=True)),
                ('Document_File', models.FileField(blank=True, null=True, upload_to=Masterlist.models.Master_Documents.get_upload_path)),
                ('Remarks', models.CharField(blank=True, max_length=256, null=True)),
                ('Rev_Details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Masterlist.rev_history')),
            ],
        ),
    ]
