# Generated by Django 3.2.18 on 2023-05-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masterlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_documents',
            name='Department',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
