# Generated by Django 3.2.18 on 2023-03-07 14:13

from django.db import migrations, models
import django.db.models.deletion
import drawings.models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0004_auto_20230223_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Development_Drawings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Uploaded', models.DateTimeField(auto_now=True)),
                ('Model_Name', models.CharField(blank=True, max_length=256, null=True)),
                ('Part_Name', models.CharField(blank=True, max_length=256, null=True)),
                ('Drawing1', models.FileField(blank=True, null=True, upload_to=drawings.models.Development_Drawings.get_upload_path)),
                ('Drawing2', models.FileField(blank=True, null=True, upload_to=drawings.models.Development_Drawings.get_upload_path)),
                ('Photo1', models.FileField(blank=True, null=True, upload_to=drawings.models.Development_Drawings.get_upload_path)),
                ('Fesability_comments', models.TextField(blank=True, null=True)),
                ('Inspection_report1', models.FileField(blank=True, null=True, upload_to=drawings.models.Development_Drawings.get_upload_path)),
                ('Inspection_report2', models.FileField(blank=True, null=True, upload_to=drawings.models.Development_Drawings.get_upload_path)),
                ('Sample_details', models.CharField(blank=True, max_length=256, null=True)),
                ('Process_Instructions', models.CharField(blank=True, help_text='optional', max_length=256, null=True)),
                ('Customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drawings.customer')),
            ],
        ),
    ]
