# Generated by Django 3.2.18 on 2023-03-29 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Capa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('Customer', models.CharField(max_length=256)),
                ('Part_name', models.CharField(max_length=256)),
                ('Sub_assembly', models.CharField(blank=True, max_length=256, null=True)),
                ('Type_of_reporting', models.CharField(blank=True, choices=[('Complaint', 'Complaint'), ('Information', 'Information')], default='Information', max_length=256, null=True)),
                ('Issue_reported', models.CharField(max_length=256)),
                ('Defect_photo', models.FileField(blank=True, null=True, upload_to='capa/Defect')),
                ('Team_Involved', models.CharField(blank=True, max_length=256, null=True)),
                ('Qty_rejected', models.CharField(blank=True, max_length=256, null=True)),
                ('Containment_details', models.CharField(blank=True, max_length=256, null=True)),
                ('Containment_date', models.DateTimeField(blank=True, null=True)),
                ('Reason_or_Root_cause', models.TextField(blank=True, null=True)),
                ('Action', models.TextField(blank=True, null=True)),
                ('Action_photo', models.FileField(blank=True, null=True, upload_to='capa/Action')),
                ('Action_date', models.DateTimeField(blank=True, null=True)),
                ('CAPA_submission_date', models.DateTimeField(blank=True, null=True)),
                ('Status', models.CharField(blank=True, choices=[('open', 'open'), ('closed', 'closed')], default='open', max_length=256, null=True)),
                ('Date_closed', models.DateTimeField(blank=True, null=True)),
                ('Process_Resp', models.CharField(blank=True, max_length=256, null=True)),
                ('Monitoring_action', models.CharField(blank=True, max_length=256, null=True)),
                ('Lesson_learnt', models.TextField(blank=True, null=True)),
                ('Audit_points', models.CharField(blank=True, max_length=256, null=True)),
                ('Remarks', models.CharField(blank=True, max_length=256)),
                ('Resp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
