# Generated by Django 3.2.18 on 2023-04-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capa',
            name='Action_report1',
            field=models.FileField(blank=True, null=True, upload_to='capa/Action'),
        ),
        migrations.AddField(
            model_name='capa',
            name='Action_report2',
            field=models.FileField(blank=True, null=True, upload_to='capa/Action'),
        ),
        migrations.AddField(
            model_name='capa',
            name='Action_report3',
            field=models.FileField(blank=True, null=True, upload_to='capa/Action'),
        ),
    ]
