# Generated by Django 3.2.18 on 2023-04-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capa', '0003_auto_20230422_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capa',
            name='action_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='capa',
            name='capa_submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='capa',
            name='containment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='capa',
            name='date_closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
