# Generated by Django 3.2.18 on 2023-05-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capa', '0005_auto_20230511_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capa',
            name='New_or_repeated',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Repeated', 'Repeated')], default='New', max_length=256, null=True),
        ),
    ]
