# Generated by Django 3.2.18 on 2023-02-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calibration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instruments_list',
            old_name='FN',
            new_name='Remarks',
        ),
        migrations.RemoveField(
            model_name='instruments_list',
            name='Intrument_ID',
        ),
        migrations.AddField(
            model_name='fixture_list',
            name='Asset_details',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fixture_list',
            name='Status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Conditionally_accepted', 'Conditionally_accepted'), ('Not_verified', 'Not_verified')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instruments_list',
            name='Status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Conditionally_accepted', 'Conditionally_accepted'), ('Not_Claibrated', 'Not_calibrated')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
