# Generated by Django 3.2.18 on 2023-02-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calibration', '0002_auto_20230223_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checksheet',
            name='Check_point1',
        ),
        migrations.RemoveField(
            model_name='checksheet',
            name='Check_point2',
        ),
        migrations.RemoveField(
            model_name='fixture_list',
            name='checksheet',
        ),
        migrations.AlterField(
            model_name='fixture_list',
            name='Asset_details',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='instruments_list',
            name='Remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Checkpoint',
        ),
        migrations.DeleteModel(
            name='CheckSheet',
        ),
    ]
