# Generated by Django 3.2.18 on 2023-02-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calibration', '0003_auto_20230223_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer', models.CharField(blank=True, max_length=256, null=True)),
                ('Product_description', models.CharField(blank=True, max_length=100, null=True)),
                ('Sub_Assembly', models.CharField(blank=True, max_length=100, null=True)),
                ('Fixture_or_Template_ID', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.CharField(blank=True, max_length=100, null=True)),
                ('Location_used', models.CharField(blank=True, max_length=100, null=True)),
                ('Verification_Freq', models.IntegerField()),
                ('Verification_Plan', models.DateField(blank=True, null=True)),
                ('Verified_on', models.DateField(blank=True, null=True)),
                ('Next_Verification_Due', models.DateField(blank=True, editable=False, null=True)),
                ('Status', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Conditionally_accepted', 'Conditionally_accepted'), ('Not_verified', 'Not_verified')], max_length=100)),
                ('Remarks', models.CharField(blank=True, max_length=256, null=True)),
                ('Asset_details', models.CharField(blank=True, max_length=50, null=True)),
                ('Verification_report1', models.FileField(blank=True, null=True, upload_to='Calibration/Fixture_or_Templates')),
                ('Verification_report2', models.FileField(blank=True, null=True, upload_to='Calibration/Fixture_or_Templates')),
            ],
        ),
    ]
