# Generated by Django 3.2.18 on 2023-02-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calibration', '0004_template_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruments_list',
            name='Location_used',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
