# Generated by Django 3.2.18 on 2023-05-12 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Calibration', '0007_auto_20230407_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='History_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Format_No', models.CharField(default='F/QA/10   Rev 01 dt 20.01.23', editable=False, max_length=100)),
                ('Date', models.DateField(auto_now=True, null=True)),
                ('Intrument_Serial_No', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.CharField(blank=True, max_length=100, null=True)),
                ('Calibrated_on', models.DateField(blank=True, null=True)),
                ('Calibrated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('Status', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Conditionally_accepted', 'Conditionally_accepted'), ('Not_Calibrated', 'Not_calibrated')], max_length=100)),
                ('Remarks', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='instruments_list',
            name='Calibration_history1',
        ),
        migrations.RemoveField(
            model_name='instruments_list',
            name='Calibration_history10',
        ),
        migrations.RemoveField(
            model_name='instruments_list',
            name='Calibration_history2',
        ),
        migrations.RemoveField(
            model_name='instruments_list',
            name='Calibration_history3',
        ),
        migrations.RemoveField(
            model_name='instruments_list',
            name='Calibration_history4',
        ),
        migrations.RemoveField(
            model_name='instruments_list',
            name='Calibration_history5',
        ),
        migrations.RemoveField(
            model_name='instruments_list',
            name='Calibration_history6',
        ),
        migrations.RemoveField(
            model_name='instruments_list',
            name='Calibration_history7',
        ),
        migrations.RemoveField(
            model_name='instruments_list',
            name='Calibration_history8',
        ),
        migrations.RemoveField(
            model_name='instruments_list',
            name='Calibration_history9',
        ),
        migrations.AddField(
            model_name='instruments_list',
            name='History',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Calibration.history_card'),
        ),
    ]
