# Generated by Django 3.2.18 on 2023-03-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0002_alter_notification_action_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='Action_taken',
            field=models.TextField(blank=True, null=True),
        ),
    ]
